#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlindRiver.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9B4CDA_webdevelopment")]
	public partial class SurveysDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSurvey(Survey instance);
    partial void UpdateSurvey(Survey instance);
    partial void DeleteSurvey(Survey instance);
    #endregion
		
		public SurveysDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_9B4CDA_webdevelopmentConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SurveysDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveysDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveysDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveysDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Survey> Surveys
		{
			get
			{
				return this.GetTable<Survey>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Surveys")]
	public partial class Survey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Question1;
		
		private string _Answer1;
		
		private string _Question2;
		
		private string _Answer2;
		
		private string _Question3;
		
		private string _Answer3;
		
		private string _Question4;
		
		private string _Answer4;
		
		private string _Question5;
		
		private string _Answer5;
		
		private string _Question6;
		
		private string _Answer6;
		
		private string _Question7;
		
		private string _Answer7;
		
		private string _Question8;
		
		private string _Answer8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnQuestion1Changing(string value);
    partial void OnQuestion1Changed();
    partial void OnAnswer1Changing(string value);
    partial void OnAnswer1Changed();
    partial void OnQuestion2Changing(string value);
    partial void OnQuestion2Changed();
    partial void OnAnswer2Changing(string value);
    partial void OnAnswer2Changed();
    partial void OnQuestion3Changing(string value);
    partial void OnQuestion3Changed();
    partial void OnAnswer3Changing(string value);
    partial void OnAnswer3Changed();
    partial void OnQuestion4Changing(string value);
    partial void OnQuestion4Changed();
    partial void OnAnswer4Changing(string value);
    partial void OnAnswer4Changed();
    partial void OnQuestion5Changing(string value);
    partial void OnQuestion5Changed();
    partial void OnAnswer5Changing(string value);
    partial void OnAnswer5Changed();
    partial void OnQuestion6Changing(string value);
    partial void OnQuestion6Changed();
    partial void OnAnswer6Changing(string value);
    partial void OnAnswer6Changed();
    partial void OnQuestion7Changing(string value);
    partial void OnQuestion7Changed();
    partial void OnAnswer7Changing(string value);
    partial void OnAnswer7Changed();
    partial void OnQuestion8Changing(string value);
    partial void OnQuestion8Changed();
    partial void OnAnswer8Changing(string value);
    partial void OnAnswer8Changed();
    #endregion
		
		public Survey()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question1", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question1
		{
			get
			{
				return this._Question1;
			}
			set
			{
				if ((this._Question1 != value))
				{
					this.OnQuestion1Changing(value);
					this.SendPropertyChanging();
					this._Question1 = value;
					this.SendPropertyChanged("Question1");
					this.OnQuestion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer1
		{
			get
			{
				return this._Answer1;
			}
			set
			{
				if ((this._Answer1 != value))
				{
					this.OnAnswer1Changing(value);
					this.SendPropertyChanging();
					this._Answer1 = value;
					this.SendPropertyChanged("Answer1");
					this.OnAnswer1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question2", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question2
		{
			get
			{
				return this._Question2;
			}
			set
			{
				if ((this._Question2 != value))
				{
					this.OnQuestion2Changing(value);
					this.SendPropertyChanging();
					this._Question2 = value;
					this.SendPropertyChanged("Question2");
					this.OnQuestion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer2", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer2
		{
			get
			{
				return this._Answer2;
			}
			set
			{
				if ((this._Answer2 != value))
				{
					this.OnAnswer2Changing(value);
					this.SendPropertyChanging();
					this._Answer2 = value;
					this.SendPropertyChanged("Answer2");
					this.OnAnswer2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question3", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question3
		{
			get
			{
				return this._Question3;
			}
			set
			{
				if ((this._Question3 != value))
				{
					this.OnQuestion3Changing(value);
					this.SendPropertyChanging();
					this._Question3 = value;
					this.SendPropertyChanged("Question3");
					this.OnQuestion3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer3", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer3
		{
			get
			{
				return this._Answer3;
			}
			set
			{
				if ((this._Answer3 != value))
				{
					this.OnAnswer3Changing(value);
					this.SendPropertyChanging();
					this._Answer3 = value;
					this.SendPropertyChanged("Answer3");
					this.OnAnswer3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question4", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question4
		{
			get
			{
				return this._Question4;
			}
			set
			{
				if ((this._Question4 != value))
				{
					this.OnQuestion4Changing(value);
					this.SendPropertyChanging();
					this._Question4 = value;
					this.SendPropertyChanged("Question4");
					this.OnQuestion4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer4", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer4
		{
			get
			{
				return this._Answer4;
			}
			set
			{
				if ((this._Answer4 != value))
				{
					this.OnAnswer4Changing(value);
					this.SendPropertyChanging();
					this._Answer4 = value;
					this.SendPropertyChanged("Answer4");
					this.OnAnswer4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question5", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question5
		{
			get
			{
				return this._Question5;
			}
			set
			{
				if ((this._Question5 != value))
				{
					this.OnQuestion5Changing(value);
					this.SendPropertyChanging();
					this._Question5 = value;
					this.SendPropertyChanged("Question5");
					this.OnQuestion5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer5", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer5
		{
			get
			{
				return this._Answer5;
			}
			set
			{
				if ((this._Answer5 != value))
				{
					this.OnAnswer5Changing(value);
					this.SendPropertyChanging();
					this._Answer5 = value;
					this.SendPropertyChanged("Answer5");
					this.OnAnswer5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question6", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question6
		{
			get
			{
				return this._Question6;
			}
			set
			{
				if ((this._Question6 != value))
				{
					this.OnQuestion6Changing(value);
					this.SendPropertyChanging();
					this._Question6 = value;
					this.SendPropertyChanged("Question6");
					this.OnQuestion6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer6", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer6
		{
			get
			{
				return this._Answer6;
			}
			set
			{
				if ((this._Answer6 != value))
				{
					this.OnAnswer6Changing(value);
					this.SendPropertyChanging();
					this._Answer6 = value;
					this.SendPropertyChanged("Answer6");
					this.OnAnswer6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question7", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Question7
		{
			get
			{
				return this._Question7;
			}
			set
			{
				if ((this._Question7 != value))
				{
					this.OnQuestion7Changing(value);
					this.SendPropertyChanging();
					this._Question7 = value;
					this.SendPropertyChanged("Question7");
					this.OnQuestion7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer7", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer7
		{
			get
			{
				return this._Answer7;
			}
			set
			{
				if ((this._Answer7 != value))
				{
					this.OnAnswer7Changing(value);
					this.SendPropertyChanging();
					this._Answer7 = value;
					this.SendPropertyChanged("Answer7");
					this.OnAnswer7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question8", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Question8
		{
			get
			{
				return this._Question8;
			}
			set
			{
				if ((this._Question8 != value))
				{
					this.OnQuestion8Changing(value);
					this.SendPropertyChanging();
					this._Question8 = value;
					this.SendPropertyChanged("Question8");
					this.OnQuestion8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer8", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Answer8
		{
			get
			{
				return this._Answer8;
			}
			set
			{
				if ((this._Answer8 != value))
				{
					this.OnAnswer8Changing(value);
					this.SendPropertyChanging();
					this._Answer8 = value;
					this.SendPropertyChanged("Answer8");
					this.OnAnswer8Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
