<?xml version="1.0" encoding="utf-8"?><Database Name="DB_9B4CDA_webdevelopment" Class="SurveysDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SQL5007.Smarterasp.net;Initial Catalog=DB_9B4CDA_webdevelopment;User ID=DB_9B4CDA_webdevelopment_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_9B4CDA_webdevelopmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Surveys" Member="Surveys">
    <Type Name="Survey">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question1" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question2" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer2" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question3" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer3" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question4" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer4" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question5" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer5" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question6" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer6" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question7" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Answer7" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question8" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Answer8" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>